### PR TITLE
broccoli-transform, proper support of path-related options

### PR DESCRIPTION
**Pull request by Dremora**
* Replace broccoli-transform with broccoli-writer
* Prepend all path-related options with srcDir or destDir as per [Relative path resolution rules](http://requirejs.org/docs/optimization.html#basics).
* Update requirejs and rsvp to the latest versions

### CODE REVIEW

**Comment by dfournier** [comment]
Hi,

Thanks for your patch, there are definitely good things inside! But there is a regression about `mainConfigFile` option. You can try to compile on [plasticine](https://github.com/dfournier/plasticine), it uses this option.

**Comment by dfournier** [comment]
I had a look at requirejs documentation and especially the part you point out. What you did should indeed fix also `exclude` option. I'll have a look at my project compilation and find out why it doesn't work with your patch at latest this weekend.

Stay tuned :+1:

**Comment by Dremora** [comment]
The error I got trying to compiling plasticine is as follows:

```
Error: Error: "appDir" is not compatible with "out". Use "dir" instead. appDir is used to copy whole projects, where "out" with "baseUrl" is used to just optimize to one file.
```

In the existing commit I was overriding every single path option (so that nothing is relative to the working directory, which in case of a Broccoli build is irrelevant), and also setting `appDir` and `dir` even if they were not defined. What I didn't take into the account is the fact that `appDir`/`dir` and `out` can't co-exist. My new logic is as follows:

* Prepend `wrap.startFile`, `wrap.endFile` and `mainConfigFile` with `srcDir` only if the properties exist in the configuration file. They are optional and don't have any default values.
* Either `out` or `dir` has to be defined in the normal require.js build. However, we can make `dir` optional for a whole project build since in most cases it will simply point to the root of the new tree. So the logic is: if `out` is defined, prepend it with `destDir`. Otherwise, assume it's a whole project build and prepend `dir` with `destDir` (or set it to `destDir` if it is not defined).
* `appDir` should be always set when `dir` is set (that is, when `out` is not set).
* `baseUrl` is relative to `appDir`. However, if `appDir` is not defined (that is, when `out` is set), we should set `baseUrl` manually.

Please correct me if I made any incorrect assumptions about the behavior of require.js.

**Comment by dfournier** [comment]
I got the same error. I'll have a look tomorrow but you're definitely on the good way. I suggest you don't fix relative path resolutions in this PR because I'm really interesting in the 2 other commits.

Before fixing relative path options, I'd like to run requirejs test with broccoli-requirejs.

**Comment by Dremora** [comment]
Did you get the error in plasticine? I tried it and it works fine for me.

**Comment by dfournier** [comment]
Broccoli is on branch [v0.1.2-v0.2.0](https://github.com/dfournier/plasticine/tree/v0.1.2-v0.2.0). It works fine with current version of broccoli-requirejs but doesn't with your patch.

**Pull request closed without merging**
